version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: spokedev
      POSTGRES_PASSWORD: spoke
      POSTGRES_USER: spoke
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379
  minio:
    image: minio/minio
    restart: always
    ports:
      - 19000:9000
    volumes:
      - minio:/data
    command: server /data
    environment:
      MINIO_ACCESS_KEY: DEVACCESSKEY
      MINIO_SECRET_KEY: DEVSECRETKEY
volumes:
  postgres:
    external: false
  redis:
    external: false
  minio:
    external: false
