service: internal-spoke

frameworkVersion: ">=1.0.0 <2.0.0"

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  infrastructure: ${opt:infrastructure, env:INFRASTRUCTURE, "dev"}
  baseUrl:
    dev: https://${self:custom.customDomain.domainName}
    prod: https://spoke.elizabethwarren.com
  debugApollo:
    dev: 1
    prod: 0
  reservedConcurrency:
    dev: 100
    prod: 1000
  # uncomment suppressPhoneValidation, dropMessageRatio
  # and skipTwilioAndAutoreply and equivalent env vars below
  # suppressPhoneValidation:
    # dev: 1
  # dropMessageRatio:
    # dev: 0.9
  # skipTwilioAndAutoReply:
    # dev: 1
  deploy:
    bucket_name: ${ssm:/${self:custom.infrastructure}/s3/deploy-artifacts/bucket/name~true}
    bucket_arn: ${ssm:/${self:custom.infrastructure}/s3/deploy-artifacts/bucket/arn~true}
  vpcConfig:
    subnetIds:
      - "${ssm:/tf/${self:custom.infrastructure}/vpc/subnets/private/id/0~true}"
      - "${ssm:/tf/${self:custom.infrastructure}/vpc/subnets/private/id/1~true}"
      - "${ssm:/tf/${self:custom.infrastructure}/vpc/subnets/private/id/2~true}"
    securityGroupIds:
      - "${ssm:/tf/${self:custom.infrastructure}/vpc/security-group/default/id~true}"
  associateWaf:
    name: ${self:custom.infrastructure}-waf-global
  customDomain:
    domainName: "${self:custom.stage}-spoke.elizabethwarren.codes"
    stage: ${self:custom.stage}
    certificateName: "*.elizabethwarren.codes"
    createRoute53Record: true
    securityPolicy: tls_1_2
  custom:
    prune:
      automatic: true
      number: 5

provider:
  name: aws
  runtime: nodejs12.x
  deploymentBucket:
    name: ${self:custom.deploy.bucket_name}
    blockPublicAccess: true
  iamRoleStatements:
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource: "arn:aws:lambda:${self:custom.region}:445320746747:function:internal-spoke-${self:custom.stage}-worker"
    - Effect: Allow
      Action:
        - "events:PutEvents"
        - "cloudwatch:PutMetricData"
      Resource: "*"
    - Effect: Allow
      Action:
        - "ses:CreateTemplate"
        - "ses:SendEmail"
        - "ses:SendTemplatedEmail"
        - "ses:UpdateTemplate"
      Resource: "*"
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - "${ssm:/${self:custom.infrastructure}/s3/spoke-private/bucket/arn~true}"
        - "${ssm:/${self:custom.infrastructure}/s3/spoke-private/bucket/arn~true}/*"
    - Effect: Allow
      Action:
        - codedeploy:*
      Resource:
        - "*"
  environment:
    STAGE: ${self:custom.stage}
    INFRASTRUCTURE: ${self:custom.infrastructure}
    NODE_ENV: production
    STATIC_BASE_URL: /assets/
    SUPPRESS_SELF_INVITE: 1
    PHONE_NUMBER_COUNTRY: US
    SESSION_SECRET: ${ssm:/${self:custom.stage}/spoke/SESSION_SECRET~true}
    SUPPRESS_SEED_CALLS: 1
    KNEX_MIGRATION_DIR: ./build/server/migrations
    PASSPORT_STRATEGY: slack
    AWS_S3_BUCKET_NAME: ${ssm:/${self:custom.infrastructure}/s3/spoke-private/bucket/name~true}
    AWS_ACCESS_AVAILABLE: 1
    DEBUG_APOLLO: ${self:custom.debugApollo.${self:custom.stage}}
    AUTH0_CLIENT_ID: ${ssm:/${self:custom.stage}/spoke/auth0/CLIENT_ID~true}
    AUTH0_CLIENT_SECRET: ${ssm:/${self:custom.stage}/spoke/auth0/CLIENT_SECRET~true}
    AUTH0_DOMAIN: ${ssm:/${self:custom.stage}/spoke/auth0/DOMAIN}
    DST_REFERENCE_TIMEZONE: America/New_York
    DEFAULT_SERVICE: twilio
    DB_HOST: ${ssm:/${self:custom.stage}/spoke/postgres/HOST~true}
    DB_NAME: ${ssm:/${self:custom.stage}/spoke/postgres/DATABASE~true}
    DB_PORT: 5432
    DB_TYPE: pg
    DB_USER: ${ssm:/${self:custom.stage}/spoke/postgres/USER~true}
    DB_PASSWORD: ${ssm:/${self:custom.stage}/spoke/postgres/PASSWORD~true}
    EMAIL_ENABLED: true
    EMAIL_FROM: ${ssm:/${self:custom.stage}/spoke/EMAIL_FROM~true}
    EMAIL_REPLY_TO: ${ssm:/${self:custom.stage}/spoke/EMAIL_REPLY_TO~true}
    SES_REGION: us-east-1
    REDIS_URL: redis://${ssm:/${self:custom.stage}/redis_cache/PRIMARY_ENDPOINT~true}:6379/3
    CACHE_PREFIX: spoke-
    TWILIO_ACCOUNT_SID: ${ssm:/${self:custom.stage}/spoke/TWILIO_ACCOUNT_SID~true}
    CONTACTS_PER_PHONE_NUMBER: 200
    TWILIO_AUTH_TOKEN: ${ssm:/${self:custom.stage}/spoke/TWILIO_AUTH_TOKEN~true}
    TWILIO_MESSAGE_SERVICE_SID: ${ssm:/${self:custom.stage}/spoke/TWILIO_MESSAGE_SERVICE_SID~true}
    TWILIO_STATUS_CALLBACK_URL: ${self:custom.baseUrl.${self:custom.stage}}/twilio-message-report
    TWILIO_VOICE_URL: ${ssm:/${self:custom.stage}/spoke/TWILIO_VOICE_URL~true}
    JOB_EXECUTOR: LAMBDA
    JOB_LAMBDA_WORKER_FUNCTION_NAME: internal-spoke-${self:custom.stage}-worker
    ASSETS_DIR: ./build/client/assets
    ASSETS_MAP_FILE: assets.json
    BASE_URL: ${self:custom.baseUrl.${self:custom.stage}}
    OPTOUTS_SHARE_ALL_ORGS: 1
    SLACK_CLIENT_ID: ${ssm:/${self:custom.stage}/spoke/slack/CLIENT_ID~true}
    SLACK_CLIENT_SECRET: ${ssm:/${self:custom.stage}/spoke/slack/CLIENT_SECRET~true}
    SLACK_TEAM_ID: ${ssm:/${self:custom.stage}/spoke/slack/TEAM_ID~true}
    EMBEDDED_SHIFTER_URL: ${ssm:/${self:custom.stage}/spoke/shifter/URL~true}
    SENTRY_DSN: ${ssm:/shared/spoke/sentry/DSN~true}
    MAX_CONTACTS: 75000
    ASSET_DOMAIN: https://ew-spoke-public.elizabethwarren.codes/${self:custom.stage}
    SLOW_REQUEST_LOG_THRESHOLD: 500
    CLOUDWATCH_METRICS_ENABLED: 1
    SUPPRESS_PHONE_VALIDATION: 1
    # SKIP_TWILIO_AND_AUTOREPLY: ${self:custom.skipTwilioAndAutoReply.${self:custom.stage}}
    # DROP_MESSAGE_RATIO: ${self:custom.dropMessageRatio.${self:custom.stage}}

functions:
  api:
    handler: lambda.handler
    vpc: ${self:custom.vpcConfig}
    events:
      - http: ANY /
      - http: ANY {proxy+}
    reservedConcurrency: ${self:custom.reservedConcurrency.${self:custom.stage}}
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live
      preTrafficHook: preflight
      postTrafficHook: postflight
    dependsOn:
      - PreflightLambdaFunction
      - PostflightLambdaFunction
  worker:
    handler: build/server/server/lambda/worker.handler
    vpc: ${self:custom.vpcConfig}
    timeout: 600
#  twilio-webhook:
#    handler: build/server/server/lambda/twilio-webhook.handler
#    vpc: ${self:custom.vpcConfig}
#    events:
#      - sqs:
#          arn: ${ssm:/${self:custom.stage}/spoke/sqs/TWILIO_WEBHOOK_QUEUE_ARN~true}
#          batchSize: 1 # TODO: this is for testing, raise it in production
  send-reminders:
    handler: build/server/server/lambda/send-reminders.handler
    vpc: ${self:custom.vpcConfig}
    timeout: 900
    events:
      - schedule: cron(0 1,17 * * ? *)
  preflight:
    handler: build/server/server/lambda/codedeploy.preflight
    vpc: ${self:custom.vpcConfig}
    timeout: 600
  postflight:
    handler: build/server/server/lambda/codedeploy.postflight
    vpc: ${self:custom.vpcConfig}
    timeout: 600

plugins:
  - serverless-domain-manager
  - serverless-associate-waf
  - serverless-api-compression
  - serverless-prune-plugin
  - serverless-jetpack
  - serverless-plugin-canary-deployments
  - serverless-plugin-git-variables

package:
  excludeDevDependencies: true
  package:
  exclude:
    - "*"
    - "webpack/**"
    - ".github/**"
    - "dev-tools/**"
    - "docs/**"
    - "__test__/**"
    - "__mocks__/**"
    - "**/node_modules/aws-sdk/**" # included on Lambda.
    - "!package.json"
    - "!lambda.js"
    - "!knexfile.js"
    - "build/client/assets/*.js"
    - "build/client/assets/*.js.map"
