name: 'Test'

# ALWAYS USE SINGLE QUOTES HERE

on: push

jobs:
  deploy:
    name: Deploy Spoke
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: spoke_test
          POSTGRES_PASSWORD: spoke_test
          POSTGRES_DB: spoke_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      STAGE: dev
      INFRASTRUCTURE: dev
      OUTPUT_DIR: ./build
      ASSETS_DIR: ./build/client/assets
      ASSETS_MAP_FILE: assets.json
      PHONE_NUMBER_COUNTRY: US
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.18.x
      - name: Install Dependencies
        run: make install-deps
      - name: Test
        run: yarn test
